### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by veend** [veend/pig-dice-game#1]
# Descriptions

- Setting basic files
- Updating READMD.md

---

## Tasks

- [x]  Update README.md
- [x]  Create .gitignore and set up ignore
- [x]  Create index.html
- [x]  Create app.js
- [x]  Create main.css
